/**
 * nGenius ACT OMR Detector
 * 
 * Pure pixel-based optical mark recognition.
 * No AI. Works by:
 *   1. Converting input image/PDF to greyscale PNG
 *   2. Finding the 3 registration marks (black squares in corners)
 *   3. Computing a homography transform to correct for rotation/scale/perspective
 *   4. Sampling pixel darkness at each bubble's known grid position
 *   5. Returning the darkest bubble per question as the answer
 * 
 * Registration marks must be clearly printed filled black squares.
 * Grid coordinates come from bubble-grid.json (generated by generate_sheet.py).
 */

import sharp from 'sharp';
import { readFileSync, writeFileSync, mkdtempSync, rmSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { tmpdir } from 'os';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Configuration ──────────────────────────────────────────────────────────
const SAMPLE_R    = 3;    // radius in pixels to sample around bubble center
const DARK_THRESH = 100;  // pixel value 0-255; below = dark/filled
const FILL_RATIO  = 0.15; // fraction of sampled pixels that must be dark to count as filled
const SCAN_DPI    = 200;  // DPI for PDF→PNG conversion

/**
 * Convert input file (PDF or image) to greyscale PNG buffer at SCAN_DPI.
 */
async function toGreyscalePNG(inputPath) {
  const ext = inputPath.toLowerCase().split('.').pop();
  let pngPath = inputPath;

  if (ext === 'pdf') {
    const tmpDir = mkdtempSync(join(tmpdir(), 'omr-'));
    try {
      const outPrefix = join(tmpDir, 'page');
      execSync(`pdftoppm -png -r ${SCAN_DPI} -f 1 -l 1 "${inputPath}" "${outPrefix}"`, { timeout: 15000 });
      const files = readdirSync(tmpDir).filter(f => f.endsWith('.png'));
      if (!files.length) throw new Error('pdftoppm produced no output');
      pngPath = join(tmpDir, files[0]);
    } catch (e) {
      // Fallback to ImageMagick
      pngPath = join(tmpDir, 'page.png');
      execSync(`magick -density ${SCAN_DPI} "${inputPath}[0]" -quality 95 "${pngPath}"`, { timeout: 15000 });
    }
  }

  const { data, info } = await sharp(pngPath)
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  return { data, width: info.width, height: info.height, dpi: SCAN_DPI };
}

/**
 * Sample average pixel darkness in a circle of radius SAMPLE_R around (px, py).
 * Returns fraction of pixels below DARK_THRESH (0 = bright, 1 = all dark).
 */
function sampleDarkness(data, width, height, px, py) {
  let dark = 0, total = 0;
  const r2 = SAMPLE_R * SAMPLE_R;
  for (let dy = -SAMPLE_R; dy <= SAMPLE_R; dy++) {
    for (let dx = -SAMPLE_R; dx <= SAMPLE_R; dx++) {
      if (dx*dx + dy*dy > r2) continue;
      const x = Math.round(px + dx);
      const y = Math.round(py + dy);
      if (x < 0 || x >= width || y < 0 || y >= height) continue;
      total++;
      if (data[y * width + x] < DARK_THRESH) dark++;
    }
  }
  return total > 0 ? dark / total : 0;
}

/**
 * Find a registration mark near the expected position.
 * Searches a window around (expectedX, expectedY) for the darkest dense region.
 * Returns {x, y} center of the found mark.
 */
function findRegMark(data, width, height, expectedX, expectedY, markSizePt, pdfW, pdfH) {
  // Convert PDF points to pixel coordinates
  // PDF coords: (0,0) = bottom-left, y increases up
  // Image coords: (0,0) = top-left, y increases down
  const scaleX = width / pdfW;
  const scaleY = height / pdfH;

  const px = Math.round(expectedX * scaleX);
  const py = Math.round((pdfH - expectedY - markSizePt) * scaleY);
  const markPx = Math.round(markSizePt * scaleX);

  // Search window: ±40px around expected position
  const WIN = 40;
  let bestDark = 0, bestX = px, bestY = py;

  for (let sy = Math.max(0, py - WIN); sy < Math.min(height - markPx, py + WIN); sy += 2) {
    for (let sx = Math.max(0, px - WIN); sx < Math.min(width - markPx, px + WIN); sx += 2) {
      // Sample a patch the size of the reg mark
      let dark = 0, total = 0;
      for (let dy = 0; dy < markPx; dy++) {
        for (let dx = 0; dx < markPx; dx++) {
          const v = data[(sy + dy) * width + (sx + dx)];
          if (v < 80) dark++;
          total++;
        }
      }
      const ratio = dark / total;
      if (ratio > bestDark) {
        bestDark = ratio;
        bestX = sx + markPx / 2;
        bestY = sy + markPx / 2;
      }
    }
  }

  return { x: bestX, y: bestY, confidence: bestDark };
}

/**
 * Given 3 registration mark positions (found in image) and their known PDF coordinates,
 * compute affine transform parameters to map PDF coords → image pixel coords.
 */
function computeTransform(regFound, regExpected, pdfW, pdfH, imgW, imgH) {
  // We have 3 point pairs. Use them to compute 2D affine transform.
  // Transform: [px, py] = A * [pdf_x, pdf_y] + b
  // But PDF y is flipped. We work in normalized PDF space first.

  // Convert PDF coords to "image-space PDF" (flip y)
  const toPdfImg = (ptPDF) => ({
    x: ptPDF[0],
    y: pdfH - ptPDF[1] - 1  // flip y
  });

  const src = regExpected.map(p => toPdfImg(p));
  const dst = regFound;

  // Solve affine: [dst_x, dst_y] = [a,b,c; d,e,f] * [src_x, src_y, 1]
  // Using 3 point pairs (exact solution)
  const [s0, s1, s2] = src;
  const [d0, d1, d2] = dst;

  // Build 3x3 system for x: [s0.x s0.y 1; s1.x s1.y 1; s2.x s2.y 1] * [a,b,c]^T = [d0.x,d1.x,d2.x]
  const det = s0.x*(s1.y-s2.y) - s0.y*(s1.x-s2.x) + (s1.x*s2.y - s2.x*s1.y);
  if (Math.abs(det) < 0.001) {
    // Degenerate — fall back to simple scale/shift using TL point
    const scaleX = imgW / pdfW;
    const scaleY = imgH / pdfH;
    return { a: scaleX, b: 0, c: 0, d: 0, e: scaleY, f: 0 };
  }

  const a = ((d0.x*(s1.y-s2.y) - s0.y*(d1.x-d2.x) + (d1.x*s2.y - d2.x*s1.y))) / det;
  const b = ((s0.x*(d1.x-d2.x) - d0.x*(s1.x-s2.x) + (d1.x*s2.x - d2.x*s1.x) )) / (-det);
  const c_  = ((s0.x*(s1.y*d2.x - s2.y*d1.x) - s0.y*(s1.x*d2.x-s2.x*d1.x) + (s1.x*s2.y-s2.x*s1.y)*d0.x)) / det;

  const d = ((d0.y*(s1.y-s2.y) - s0.y*(d1.y-d2.y) + (d1.y*s2.y - d2.y*s1.y))) / det;
  const e = ((s0.x*(d1.y-d2.y) - d0.y*(s1.x-s2.x) + (d1.y*s2.x - d2.y*s1.x))) / (-det);
  const f  = ((s0.x*(s1.y*d2.y - s2.y*d1.y) - s0.y*(s1.x*d2.y-s2.x*d1.y) + (s1.x*s2.y-s2.x*s1.y)*d0.y)) / det;

  return { a, b, c: c_, d, e, f };
}

/**
 * Apply affine transform to convert PDF coordinates to image pixel coordinates.
 */
function pdfToImg(pdfX, pdfY, transform, pdfH) {
  const sx = pdfX;
  const sy = pdfH - pdfY - 1;  // flip y (PDF bottom-left → image top-left)
  const { a, b, c, d, e, f } = transform;
  return {
    x: a * sx + b * sy + c,
    y: d * sx + e * sy + f
  };
}

/**
 * Main OMR function.
 * @param {string} imagePath - Path to image or PDF
 * @param {object} grid - Contents of bubble-grid.json
 * @returns {object} answers: { english: ['C','G',...], math: [...], reading: [...], science: [...] }
 */
export async function detectAnswers(imagePath, grid) {
  const { data, width, height } = await toGreyscalePNG(imagePath);
  const [pdfW, pdfH] = grid.page_size;
  const { TL, TR, BL, size: markSize } = grid.reg_marks;

  // Find actual registration mark positions in image
  const regFound = [
    findRegMark(data, width, height, TL[0], TL[1], markSize, pdfW, pdfH),
    findRegMark(data, width, height, TR[0], TR[1], markSize, pdfW, pdfH),
    findRegMark(data, width, height, BL[0], BL[1], markSize, pdfW, pdfH),
  ];

  // Expected PDF coords of mark centers
  const regExpected = [
    [TL[0] + markSize/2, TL[1] + markSize/2],
    [TR[0] + markSize/2, TR[1] + markSize/2],
    [BL[0] + markSize/2, BL[1] + markSize/2],
  ];

  const avgConf = regFound.reduce((s, r) => s + r.confidence, 0) / 3;
  console.log(`Reg marks found: TL(${Math.round(regFound[0].x)},${Math.round(regFound[0].y)}) TR(${Math.round(regFound[1].x)},${Math.round(regFound[1].y)}) BL(${Math.round(regFound[2].x)},${Math.round(regFound[2].y)}) confidence=${avgConf.toFixed(2)}`);

  const transform = computeTransform(
    regFound.map(r => ({x: r.x, y: r.y})),
    regExpected,
    pdfW, pdfH, width, height
  );

  const answers = {};

  for (const [section, qmap] of Object.entries(grid.sections)) {
    const sectionAnswers = [];
    const sortedQnums = Object.keys(qmap).map(Number).sort((a,b) => a-b);

    for (const qnum of sortedQnums) {
      const bubbleCenters = qmap[qnum]; // [[cx,cy], [cx,cy], [cx,cy], [cx,cy]]
      const choices = qnum % 2 === 1 ? ['A','B','C','D'] : ['F','G','H','J'];

      let maxDark = 0, bestChoice = '?';

      for (let i = 0; i < bubbleCenters.length; i++) {
        const [pdfX, pdfY] = bubbleCenters[i];
        const { x: imgX, y: imgY } = pdfToImg(pdfX, pdfY, transform, pdfH);
        const darkness = sampleDarkness(data, width, height, imgX, imgY);

        if (darkness > maxDark) {
          maxDark = darkness;
          bestChoice = choices[i];
        }
      }

      // Only accept if the darkest bubble is actually dark enough
      if (maxDark < FILL_RATIO) bestChoice = '?';

      sectionAnswers.push(bestChoice);
    }

    answers[section] = sectionAnswers;
  }

  return answers;
}

// ── CLI test mode ──────────────────────────────────────────────────────────
if (process.argv[2]) {
  const imagePath = process.argv[2];
  const gridPath = process.argv[3] || join(__dirname, 'public/bubble-grid.json');
  const grid = JSON.parse(readFileSync(gridPath, 'utf8'));

  console.log(`Processing: ${imagePath}`);
  detectAnswers(imagePath, grid)
    .then(answers => {
      console.log('\nExtracted answers:');
      for (const [sec, ans] of Object.entries(answers)) {
        const unknowns = ans.filter(a => a === '?').length;
        console.log(`  ${sec}: [${ans.join(',')}] (${unknowns} unknown)`);
      }
    })
    .catch(err => console.error('Error:', err.message));
}
